# -*- coding: utf-8 -*-
"""CodePark_2 - 31/10/22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-7szx9kPq2kXT4y_bqCadFBvXx7g_0GK
"""

def calc_idade(ano_nasc):
   hoje = 2022 - ano_nasc
   
   return hoje

print("--------Dados de usuário -------\n")
a = True
while a :
  
  nome = input(' Digite o nome completo do usuário:')
  try:
   ano_nas = int(input(' Digite o ano de nascimento:'))

   if  ((ano_nas >= 1922) and (ano_nas <= 2022)):
    idade = calc_idade(ano_nas)
    
    print(' Nome do usuário:',nome)
    print(' Idade do usuário:',idade)
    break
   else:
    print("--->> Ano de nascimento a partir de 1922 até 2022")
  except Exception as b:
   print("Dado incorreto --->>> ", b)